server:
  port: ${APP_PORT}

spring:
  application:
    name: server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
  liquibase:
    change-log: classpath:db/db_changelog-master.yaml

jwt:
  dev-token: my-secret-jwt
  dev: true
  secret: my-secret-jwt

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html